# fly.toml app configuration file generated for propellant-hr on 2025-06-30T21:20:25+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'propellant-fe'
primary_region = 'jnb'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
